const lgbtPageContent = {
  data: {
    id: 1,
    createdAt: "2023-02-13T10:27:05.125Z",
    updatedAt: "2023-03-06T08:45:21.834Z",
    publishedAt: "2023-02-13T10:27:06.817Z",
    name: "lgbt",
    pageContent: [
      {
        id: 1,
        __component: "layout.hero",
        title: "Queer, Trans & Non-Binary",
        subtitle: "Toys for every body",
        image: {
          id: 3,
          name: "lgbt-hero.png",
          alternativeText: "person holding umbrella in the rain",
          caption: null,
          width: 1512,
          height: 501,
          formats: {
            large: {
              ext: ".png",
              url: "https://res.cloudinary.com/dxrvqywct/image/upload/v1676311801/large_lgbt_hero_935d5f5f1f.png",
              hash: "large_lgbt_hero_935d5f5f1f",
              mime: "image/png",
              name: "large_lgbt-hero.png",
              path: null,
              size: 586.65,
              width: 1000,
              height: 331,
              provider_metadata: {
                public_id: "large_lgbt_hero_935d5f5f1f",
                resource_type: "image",
              },
            },
            small: {
              ext: ".png",
              url: "https://res.cloudinary.com/dxrvqywct/image/upload/v1676311801/small_lgbt_hero_935d5f5f1f.png",
              hash: "small_lgbt_hero_935d5f5f1f",
              mime: "image/png",
              name: "small_lgbt-hero.png",
              path: null,
              size: 169.16,
              width: 500,
              height: 166,
              provider_metadata: {
                public_id: "small_lgbt_hero_935d5f5f1f",
                resource_type: "image",
              },
            },
            medium: {
              ext: ".png",
              url: "https://res.cloudinary.com/dxrvqywct/image/upload/v1676311801/medium_lgbt_hero_935d5f5f1f.png",
              hash: "medium_lgbt_hero_935d5f5f1f",
              mime: "image/png",
              name: "medium_lgbt-hero.png",
              path: null,
              size: 352.01,
              width: 750,
              height: 249,
              provider_metadata: {
                public_id: "medium_lgbt_hero_935d5f5f1f",
                resource_type: "image",
              },
            },
            thumbnail: {
              ext: ".png",
              url: "https://res.cloudinary.com/dxrvqywct/image/upload/v1676311801/thumbnail_lgbt_hero_935d5f5f1f.png",
              hash: "thumbnail_lgbt_hero_935d5f5f1f",
              mime: "image/png",
              name: "thumbnail_lgbt-hero.png",
              path: null,
              size: 45.79,
              width: 245,
              height: 81,
              provider_metadata: {
                public_id: "thumbnail_lgbt_hero_935d5f5f1f",
                resource_type: "image",
              },
            },
          },
          hash: "lgbt_hero_935d5f5f1f",
          ext: ".png",
          mime: "image/png",
          size: 271.55,
          url: "https://res.cloudinary.com/dxrvqywct/image/upload/v1676311801/lgbt_hero_935d5f5f1f.png",
          previewUrl: null,
          provider: "cloudinary",
          provider_metadata: {
            public_id: "lgbt_hero_935d5f5f1f",
            resource_type: "image",
          },
          createdAt: "2023-02-13T18:10:02.082Z",
          updatedAt: "2023-02-22T13:20:58.777Z",
        },
      },
      {
        id: 1,
        __component: "layout.lgbt-intro",
        title: null,
        body: "Intro Body.",
        buttonText: "READ NON-BINARY & TRANS ARTICLES",
        buttonVariant: "Dark",
      },
      {
        id: 1,
        __component: "layout.strip-header",
        gradientColour: "to-gunmetal-dark",
        title: "The PULSE DUO Lux",
      },
      {
        id: 2,
        __component: "layout.call-to-action",
        title: "Sign up for emails",
        body: "Yes, I want to receive exclusive email offers, sexy advice and get 10% off my order. By Subscribing you agree to our privacy policy. We will not share or sell your personal information.",
        buttonText: "Subscribe",
        placeholder: "Your email address",
      },
    ],
  },
  meta: {},
};

export default lgbtPageContent;
