import ContentWrap from "@/components/elements/ui/ContentWrap";
import CompetitionPageNav from "@/components/sections/CompetitionPlatformPage.tsx/CompetitionPageNav.tsx/CompetitionPageNav";
import GalleryGrid from "@/components/sections/CompetitionPlatformPage.tsx/gallery/GalleryGrid";
import { useSubCategories } from "@/context/subCategories";
import { fetchAPI } from "@/lib/api";
import { ProductType, SubCategoryType } from "@/types/products";
import { GetStaticProps, InferGetStaticPropsType } from "next";
import Head from "next/head";
import React, { useEffect } from "react";

const Contestant = ({
  subcategories,
  newProducts,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const { setSubCategories, setNewProducts } = useSubCategories();
  useEffect(() => {
    setNewProducts(newProducts);
    setSubCategories(subcategories);
  }, [setSubCategories, subcategories, setNewProducts, newProducts]);
  return (
    <>
      <Head>
        <title>Contestant Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <CompetitionPageNav />
        <div className="bg-gradient-to-b from-[#E9E7E6] to-[#E7D4DB] pb-14">
          <ContentWrap className="pt-14 flex-col items-center ">
            <div className="text-5xl flex flex-col items-center">
              <div
                className="
        md:text-5xl text-4xl uppercase text-pink
        "
              >
                entry
              </div>
              <div className="font-paul text-green md:text-8xl text-7xl -mt-6">
                gallery
              </div>
            </div>
            <div className="text-brown text-center mt-10 md:mt-16 mb-8">
              <p className="md:text-lg text-md">
                Find yourself and your friends in the contestant gallery.
              </p>
              <p className="text-sm">
                {`We'll be selecting our 3 Gynaguard ambassadors from this amazing
group of ideas`}
              </p>
            </div>
            <GalleryGrid />
          </ContentWrap>
        </div>
      </div>
    </>
  );
};

export const getStaticProps: GetStaticProps<{
  subcategories: SubCategoryType[];
  newProducts: ProductType[];
}> = async (ctx) => {
  const { data: subcategories } = await fetchAPI("subcategories", ["products"]);
  const productPopulate = ["products.products.image", "products.products"];
  const { data: productsData } = await fetchAPI(
    "products-range",
    productPopulate
  );
  const products: ProductType[] =
    productsData?.attributes.products.products.data.map((product: any) => ({
      ...product?.attributes,
      id: product.id,
    }));
  const newProducts = products.filter((product) => product.isNew);
  return {
    props: {
      newProducts,
      subcategories: subcategories.map((subcategory: any) => ({
        ...subcategory?.attributes,
        id: subcategory.id,
      })),
    },
  };
};

export default Contestant;
