import CompetitionPageNav from "@/components/sections/CompetitionPlatformPage.tsx/CompetitionPageNav.tsx/CompetitionPageNav";
import EntryForm from "@/components/sections/CompetitionPlatformPage.tsx/EntryForm/EntryForm";
import HowToEnter from "@/components/sections/CompetitionPlatformPage.tsx/EntryForm/HowToEnter";
import Head from "next/head";
import React from "react";

const entry = () => {
  return (
    <>
      <Head>
        <title>Entry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <CompetitionPageNav />
        <HowToEnter />

        <EntryForm />
      </div>
    </>
  );
};

export default entry;
