import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CompetitionPageNav from "@/components/sections/CompetitionPlatformPage.tsx/CompetitionPageNav.tsx/CompetitionPageNav";
import DropDown from "@/components/elements/GallerySortDropDown";
import HomePageHero from "@/components/sections/homepage/homePageHero/HomePageHero";
import Products from "@/components/sections/homepage/products/Products";
import FeminineHygiene from "@/components/sections/homepage/feminineHygiene/FeminineHygiene";
import { ParallaxProvider } from "react-scroll-parallax";
import Articles from "@/components/sections/homepage/articles/Articles";
import GynaguardPromise from "@/components/elements/GynaguardPromise/GynaguardPromise";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ParallaxProvider>
        <main className="">
          <HomePageHero />
          <div className="mt-8 mx-8">
            <Products />
          </div>
          <div className="mt-16">
            <FeminineHygiene />
          </div>
          <div className="mt-1">
            <Articles />
          </div>
          <div>
            <GynaguardPromise />
          </div>
        </main>
      </ParallaxProvider>
    </>
  );
}
